### ISSUE TITLE
miek.nl/go is hard to read on a non-high resolution display.

### ISSUE THREAD

**Issue by kartik-ynwa** [miekg/learninggo#45]
On a 14" 1366x786 display, the text is too thin. Maybe change the weight to 400 or use a different font?

Great work by the way. Thanks for doing this.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/learninggo] miek.nl/go is ha..." ]
>On a 14" 1366x786 display, the text is too thin. Maybe change the weight to 400 or use a different font?
>
>Great work by the way. Thanks for doing this.

Thanks.

Up for having diff css. Care to send a PR?

**Comment by kartik-ynwa** [comment]
Yep . On it.

**Comment by kartik-ynwa** [comment]
Up for review.
