### ISSUE TITLE
problems with make using mmark 2.0.29

### ISSUE THREAD

**Issue by wlbr** [miekg/learninggo#59]
learninggo.html does not "compile" using the current mmark 2.0.29.

~/learninggo $ make learninggo.html
mmark -html -head inc/head.html -css inc/learninggo.css learninggo.md > learninggo.html
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x113a138]

goroutine 1 [running]:
github.com/mmarkdown/mmark/mhtml.bibliographyItem(0x11ca8e0, 0xc00030b030, 0xc0000b1400, 0xc00030b001)
	/Users/me/Library/golang/packages/src/github.com/mmarkdown/mmark/mhtml/hook.go:104 +0x298
github.com/mmarkdown/mmark/mhtml.RenderHook(0x11ca8e0, 0xc00030b030, 0x11cc880, 0xc0000b1400, 0x1, 0x0, 0xc0000d7701)
	/Users/me/Library/golang/packages/src/github.com/mmarkdown/mmark/mhtml/hook.go:37 +0x38c
github.com/gomarkdown/markdown/html.(*Renderer).RenderNode(0xc0000eec60, 0x11ca8e0, 0xc00030b030, 0x11cc880, 0xc0000b1400, 0x1, 0x0)
	/Users/me/Library/golang/packages/src/github.com/gomarkdown/markdown/html/renderer.go:914 +0x16e9
github.com/gomarkdown/markdown.Render.func1(0x11cc880, 0xc0000b1400, 0x10fd601, 0x0)
	/Users/me/Library/golang/packages/src/github.com/gomarkdown/markdown/markdown.go:63 +0x61
github.com/gomarkdown/markdown/ast.NodeVisitorFunc.Visit(0xc0002f8fa0, 0x11cc880, 0xc0000b1400, 0x1, 0x0)
	/Users/me/Library/golang/packages/src/github.com/gomarkdown/markdown/ast/node.go:545 +0x43
github.com/gomarkdown/markdown/ast.Walk(0x11cc880, 0xc0000b1400, 0x11cab60, 0xc0002f8fa0, 0x0)
	/Users/me/Library/golang/packages/src/github.com/gomarkdown/markdown/ast/node.go:517 +0x70
github.com/gomarkdown/markdown/ast.Walk(0x11cc820, 0xc00025f650, 0x11cab60, 0xc0002f8fa0, 0x0)
	/Users/me/Library/golang/packages/src/github.com/gomarkdown/markdown/ast/node.go:528 +0x1ba
github.com/gomarkdown/markdown/ast.Walk(0x11cbe00, 0xc00025e1c0, 0x11cab60, 0xc0002f8fa0, 0x0)
	/Users/me/Library/golang/packages/src/github.com/gomarkdown/markdown/ast/node.go:528 +0x1ba
github.com/gomarkdown/markdown/ast.Walk(0x11cbda0, 0xc000088420, 0x11cab60, 0xc0002f8fa0, 0xc0002f8fa0)
	/Users/me/Library/golang/packages/src/github.com/gomarkdown/markdown/ast/node.go:528 +0x1ba
github.com/gomarkdown/markdown/ast.WalkFunc(0x11cbda0, 0xc000088420, 0xc0002f8fa0)
	/Users/me/Library/golang/packages/src/github.com/gomarkdown/markdown/ast/node.go:551 +0x4b
github.com/gomarkdown/markdown.Render(0x11cbda0, 0xc000088420, 0x11cb0c0, 0xc0000eec60, 0x11a4885, 0x13, 0x11a3402)
	/Users/me/Library/golang/packages/src/github.com/gomarkdown/markdown/markdown.go:62 +0xd8
main.main()
	/Users/me/Library/golang/packages/src/github.com/mmarkdown/mmark/mmark.go:172 +0x5c6
make: *** [Makefile:7: learninggo.html] Error 2

~/learninggo $ mmark -version
2.0.29

~/learninggo $ go version
go version go1.11 darwin/amd64

**Comment by miekg** [comment]
Ha nice. should add this as a test.

Willing to fix this, if you know go?

**Comment by miekg** [comment]
Silly mistake. Pushing fix and new releases

**Comment by wlbr** [comment]
Hey thanks! You resolved the issue quicker than I read my emails again!
Great work!

Regards,
Michael

Am Mi., 24. Okt. 2018 um 20:19 Uhr schrieb Miek Gieben <
notifications@github.com>:
