### ISSUE TITLE
is there a pdf file to download

### ISSUE THREAD

**Issue by dbabits** [miekg/learninggo#60]
Is there a way to download a pdf file?
The older version on github has a link to pdf, but it's broken.
thanks

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/learninggo] is there a pdf f..." ]
>Is there a way to download a pdf file?
>The older version on github has a link to pdf, but it's broken.
>thanks

No, there isn't a pdf anymore, only html.
