### ISSUE TITLE
Make it work on mobile

### ISSUE THREAD

**Issue by miekg** [miekg/learninggo#8]
Sprinkle the css with @media.

**Comment by miekg** [comment]
The monospace <pre><code> is too small on mobile and the ui-nav is smallish too.

**Comment by antoniomo** [comment]
What would the solution be, have a bigger monospace font on small screens? Is this still an issue?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/learninggo] Make it work..." ]
>What would the solution be, have a bigger monospace font on small screens? Is this still an issue?

Yes, generally the font size is too small on mobile, esp the monospace.

**Comment by antoniomo** [comment]
I'll take a look over this or next weekend, a bit busy with Christmas preparations!
